### ISSUE TITLE
Tinker arrows dealing only minimum damage when setting the bows in the aa speed config (vanilla arrows work fine when fired from the same tinkerbow)

### ISSUE THREAD

**Issue by SirAron111** [TheRandomLabs/RandomConfigs#11] opened 2019-06-27 21:29 UTC
Random configs (probably has something to do with the attackspeed options) to make tinkers construct arrows when fired from any bow to always do the minimum damage never the maximum no mather how long you charge the bow. Probably it thinks that the arrow isn’t charged and that causes it to bug out (with charged I mean reached the max attack speed meter since arrows themselves don’t even have one only swords do)
Anyway it only does 1 dmg no matter what
And I found out xactly wht caused it so ima just here to report that.
In the attackspeed configs I set it like this and it works great for all weapons even the bows hit slower as intended to prevent them from being used as melee weapons.
But here is the twist when setting the bows and crossbow like this it causes the projectiles fired from it to do minimum damage always even if charged up. Once I removed the lines for
		tconstruct:crossbow /tconstruct:shortbow and tconstruct:longbow
The projectiles fired from them where back to normal but so was the hitting speed of the bows. Well that’s a small bug and a super rare special case so I don’t think many will notice it but I told you about it so here you go bug reported XD. I for now just took out the bows to fix the arrows.

This was my how i set it before: now i just removed the entrys for the ones stated above all other things work great and it helps a lot with the balancing to make people use the skill system to skill up attack speed or decide for more damage but be slower etc.
Great mod loving it!

{
	"attackSpeeds": {
		"tconstruct:hammer": {
			"speed": 3.5,
			"disableAttacksDuringAttackCooldown": false
		},
		"plustic:katana": {
			"speed": 2.0,
			"disableAttacksDuringAttackCooldown": false
		},
		"tconstruct:mattock": {
			"speed": 3.4,
			"disableAttacksDuringAttackCooldown": false
		},
		"tconstruct:battlesign": {
			"speed": 3.6,
			"disableAttacksDuringAttackCooldown": false
		},
		"tconstruct:frypan": {
			"speed": 3.4,
			"disableAttacksDuringAttackCooldown": false
		},
		"tconstruct:longsword": {
			"speed": 3.6,
			"disableAttacksDuringAttackCooldown": false
		},
		"tconstruct:shovel": {
			"speed": 3.3,
			"disableAttacksDuringAttackCooldown": false
		},
		"yoyos:yoyo": {
			"speed": 3.5,
			"disableAttacksDuringAttackCooldown": false
		},
		"tconstruct:excavator": {
			"speed": 3.6,
			"disableAttacksDuringAttackCooldown": false
		},
		"tconstruct:crossbow": {
			"speed": 2.3,
			"disableAttacksDuringAttackCooldown": false
		},
		"tconstruct:cleaver": {
			"speed": 3.6,
			"disableAttacksDuringAttackCooldown": false
		},
		"plustic:laser_gun": {
			"speed": 1.3,
			"disableAttacksDuringAttackCooldown": false
		},
		"tconstruct:hatchet": {
			"speed": 3.2,
			"disableAttacksDuringAttackCooldown": false
		},
		"tconstruct:scythe": {
			"speed": 3.6,
			"disableAttacksDuringAttackCooldown": false
		},
		"tconstruct:shortbow": {
			"speed": 2.8,
			"disableAttacksDuringAttackCooldown": false
		},
		"tconstruct:kama": {
			"speed": 3.0,
			"disableAttacksDuringAttackCooldown": false
		},
		"tconstruct:lumberaxe": {
			"speed": 3.5,
			"disableAttacksDuringAttackCooldown": false
		},
		"tconstruct:pickaxe": {
			"speed": 3.1,
			"disableAttacksDuringAttackCooldown": false
		},
		"tconstruct:rapier": {
			"speed": 2.4,
			"disableAttacksDuringAttackCooldown": false
		},
		"tconstruct:broadsword": {
			"speed": 3.3,
			"disableAttacksDuringAttackCooldown": false
		},
		"tconstruct:longbow": {
			"speed": 3.0,
			"disableAttacksDuringAttackCooldown": false
		}
	},
	"defaultAttackSpeed": 3.4,
	"disableAttacksDuringAttackCooldownByDefault": false,
	"asreloadCommand": true,
	"asreloadclientCommand": true,
	"enabled": true
}

**Comment by SirAron111** [comment] 2019-06-27 21:32
Have a more precise mod handling the attack prevention for not fully charged attack speed bars that’s why it’s turned to false here XD. BTW this bug was also tested with just this mod and tinkers and it still happens just to let you know.

**Comment by TheRandomLabs** [comment] 2019-10-04 07:19
A bit over three months late, I've discovered the cause of the issue. SlimeKnights/TinkersConstruct#3957

**Comment by TheRandomLabs** [comment] 2019-10-15 05:18
Fixed in Tinkers' Construct.

**Closed as completed by TheRandomLabs** 2019-10-15 05:18 UTC
